paths:
    TRAINING_CSV: ../data/raw/GTSRB_Final_Training_Images/GTSRB/Final_Training/Images/*/*.csv
    TEST_CSV: ../data/raw/GTSRB_Final_Test_Images/GTSRB/Final_Test/Images/
    TEST_GT: ../data/raw/GT-final_test.csv
    
parameters:
    IMAGE_WIDTH: 30
    IMAGE_HEIGHT: 30
    